### PR TITLE
Don't run optimize on expressions that contain datetimes or timedeltas

### PR DESCRIPTION
**Pull request by cpcloud**

### CODE REVIEW

**Comment by llllllllll** [comment]
my new test was on a branch, not master. Also; do you guys use gitter or something for blaze-dev?

**Comment by cpcloud** [comment]
we could use gitter, i'm just not sure about opening up the floodgates. we could give it a shot

**Comment by cpcloud** [comment]
> my new test was on a branch, not master.

not sure i understand this

**Comment by llllllllll** [comment]
I am trying to understand what you gain by making this PR against our fork versus upstream

**Comment by cpcloud** [comment]
i didn't want to rewrite `test_timedelta_arith`. by writing code off your `date-arith` branch, i already had a test case for the failing code. if i submitted to upstream, i'd need a test case + fix and i didn't want to rewrite the test.

**Comment by cpcloud** [comment]
this way, you have the test case and the fix and i still have my commits in there.

**Comment by llllllllll** [comment]
Ahh, sorry, I thought this was against master. I have not seen prs against branches

**Comment by cpcloud** [comment]
they are a rare breed. i only do them when collaborating with someone

**Comment by llllllllll** [comment]
Nice, this lgtm

**Comment by cpcloud** [comment]
i pulled the trigger on gitter

**Pull request merged**
